/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-30 07:37:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detailpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/ssafy/work_servlet_jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SafeFood_Web_Back_End_광주_3반_선한빛_임준형/WEB-INF/lib/jstl-1.2%20(1).jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/ssafy/work_servlet_jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SafeFood_Web_Back_End_광주_3반_선한빛_임준형/WEB-INF/lib/jstl-1.2%20(1).jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2 (1).jar", Long.valueOf(1569827813609L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>SafeFood | 상품 정보 목록</title>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../bootstrap-3.3.2-dist/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../bootstrap-3.3.2-dist/css/bootstrap-theme.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/main.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/chart.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.8.0\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <script>\r\n");
      out.write("\t\twindow.onload = function() {\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tvar url = '../bin/FoodNutritionInfo.xml';\r\n");
      out.write("\t\t\txhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\txhr.onreadystatechange = function() {\r\n");
      out.write("\t\t\t\tif (xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar resDoc = xhr.responseXML;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tfoodList = resDoc.getElementsByTagName(\"DESC_KOR\");\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tnutr1List = resDoc.getElementsByTagName(\"NUTR_CONT1\"); // 칼로리\r\n");
      out.write("\t\t\t\t\tnutr2List = resDoc.getElementsByTagName(\"NUTR_CONT2\"); // 탄수화물\r\n");
      out.write("\t\t\t\t\tnutr3List = resDoc.getElementsByTagName(\"NUTR_CONT3\"); // 단백질\r\n");
      out.write("\t\t\t\t\tnutr4List = resDoc.getElementsByTagName(\"NUTR_CONT4\"); // 지방\r\n");
      out.write("\t\t\t\t\tnutr5List = resDoc.getElementsByTagName(\"NUTR_CONT5\"); // 당류\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tvar wras = document.getElementsByClassName('wra');\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tfor (var i = 0; i < foodList.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif (foodList[i].childNodes[0].nodeValue == \"새우탕큰사발\") {\r\n");
      out.write("\t\t\t\t\t\t\twras[0].innerHTML = nutr1List[i].childNodes[0].nodeValue;\r\n");
      out.write("\t\t\t\t\t\t\twras[1].innerHTML = nutr2List[i].childNodes[0].nodeValue;\r\n");
      out.write("\t\t\t\t\t\t\twras[2].innerHTML = nutr3List[i].childNodes[0].nodeValue;\r\n");
      out.write("\t\t\t\t\t\t\twras[3].innerHTML = nutr4List[i].childNodes[0].nodeValue;\r\n");
      out.write("\t\t\t\t\t\t\twras[4].innerHTML = nutr5List[i].childNodes[0].nodeValue;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\txhr.open('GET', url, true);\r\n");
      out.write("\t\t\txhr.send();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script> -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-fixed-top\" style=\"background-color: #2e3537;\">\r\n");
      out.write("    <div class=\"col-md-1\"></div>\r\n");
      out.write("    <div class=\"col-md-10\" style=\"text-align: right;\">\r\n");
      out.write("        <button class=\"btn btn-sm dropdown-toggle glyphicon glyphicon-user\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\" style=\"background-color: #2c2c2c; color: #ffffff; margin: 7px\">&nbspLogin</button>\r\n");
      out.write("        <ul  class=\"dropdown-menu dropdown-menu-right\" style=\"border: 1px solid #252a2c; background: #2e3537;\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <form class=\"login-form margin-clear\" style=\"background: #2e3537; margin: 20px 20px;\">\r\n");
      out.write("                    <div class=\"form-group has-feedback\">\r\n");
      out.write("                        <label class=\"control-label\" style=\"color: #ffffff;\">아 이 디</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" >\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-user form-control-feedback\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group has-feedback\">\r\n");
      out.write("                        <label class=\"control-label\" style=\"color: #ffffff;\">비밀번호</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-user form-control-feedback\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-sm\" style=\"margin-bottom :20px\">로 그 인</button><br>\r\n");
      out.write("                        <a href=\"./find.html\"><button type=\"button\" class=\"btn btn-sm\" style=\"background-color: #2c2c2c; color: #ffffff;\">비밀번호 찾기</button></a>\r\n");
      out.write("                </form>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <a href=\"./signup.html\"><button class=\"btn btn-sm glyphicon glyphicon-user\" style=\"background-color: #2c2c2c; color: #ffffff; margin: 7px\">&nbsp회원가입</button></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-1\"></div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<body style=\"padding-top: 40px;\">\r\n");
      out.write("\t<!-- 메뉴바 -->\r\n");
      out.write("\t\t<div class=\"row\" style=\"background-color: #ffffff; height: 100px; margin-top: 10px;\">\r\n");
      out.write("\t\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\"><a href=\"./main.html\"><img src=\"../img/ssafy.png\" width=\"120px\"></a></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\" style=\"float: right;\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./info.html\">공지 사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./list_product.html\">상품 정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">베스트 섭취 정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">내 섭취 정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">예상 섭취 정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"glyphicon glyphicon-search\"></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 점보트론? -->\r\n");
      out.write("\t\t<div class=\"row\" style=\"background-color: #6C6C6C; height: 200px;\">\r\n");
      out.write("\t\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-10\" style=\"color: white; margin: 30px; text-align: center;\">\r\n");
      out.write("\t\t\t\t<h2>WHAT WE PROVIDE</h2>\r\n");
      out.write("\t\t\t\t<div class=\"divide-line-center\"></div>\r\n");
      out.write("\t\t\t\t<p style=\"padding:15px;\">건강한 삶을 위한 먹거리 프로젝트</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t​\r\n");
      out.write("\t<div class=\"main col-12\">\r\n");
      out.write("\t\t<h1 class=\"page-title text-center\">제품 정보</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t​\r\n");
      out.write("\t<p style=\"text-align: center;\">\r\n");
      out.write("\t\t<img src=\"../img/바구니.PNG\" width=\"100px\">\r\n");
      out.write("\t</p>\r\n");
      out.write("\t​\r\n");
      out.write("\t<div class=\"image-box style-3-b\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("\t\t\t\t<div class=\"overlay-container\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/새우탕큰사발.jpg\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t​\r\n");
      out.write("\t\t\t<div class=\"col-lg-8 col-xl-7 pv-30\">\r\n");
      out.write("\t\t\t\t<table class=\"table\" style=\"width: 600px\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100\">제품명</td>\r\n");
      out.write("\t\t\t\t\t\t<td>새우탕큰사발</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t​\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100\">제조사</td>\r\n");
      out.write("\t\t\t\t\t\t<td>농심</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t​\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100\">원재료</td>\r\n");
      out.write("\t\t\t\t\t\t<td>소맥분(호주산,미국산),감자전분(독일산),팜유,변성전분,식물성풍미유,난각칼슘,정제염,야채조미추출물,\r\n");
      out.write("\t\t\t\t\t\t\t면류첨가알칼리제 ( 산도조절제 ),혼합제제 ( 산도조절제 ),올리고녹차풍미액,비타민B₂,새우베이스분말,정제염,\r\n");
      out.write("\t\t\t\t\t\t\t정백당,육수베이스분말,매운맛분말,조미양념분,매운탕조미분말,호화옥수수분,육수맛조미베이스,오징어조미분말,\r\n");
      out.write("\t\t\t\t\t\t\t오징어풍미분말,양념구이조미분,5-리보뉴클레오티드이나트륨,분말고추장,이스트풍미분,호박산이나트륨,복합조미간장분말,\r\n");
      out.write("\t\t\t\t\t\t\t분말카라멜 ( 카라멜색소 , 물엿분말 ),다시마정미추출분말,혼합해물베이스분말,멸치조미분,향신조미분,후추가루,\r\n");
      out.write("\t\t\t\t\t\t\t다시마표고조미분,수화검 ( 구아검 , 산탄검 ),후추추출물분말,어포,새우맛볼,건미역,건당근,건새우,새우 ( 중국산\r\n");
      out.write("\t\t\t\t\t\t\t58.1% , 캐나다산 41.0% , 국내산 0.9% )</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t​\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100\">알레르기 성분</td>\r\n");
      out.write("\t\t\t\t\t\t<td>새우</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t​\r\n");
      out.write("\t\t\t\t<form class=\"clearfix row grid-space-10\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" style=\"width: 600px\">\r\n");
      out.write("\t\t\t\t\t\t<label>Quantity</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"qnt\" name=\"qnt\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t​\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-info\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/add.png\" width=\"15px\"> 추가\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-info\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/heart.png\" width=\"15px\"> 찜\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"main col-12\">\r\n");
      out.write("\t\t<h1 class=\"page-title text-center\">영양 정보</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"q2_2010\">\r\n");
      out.write("\t\t\t<div id=\"labels\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><span></span>칼로리</li>\r\n");
      out.write("\t\t\t\t\t<li><span></span>탄수화물</li>\r\n");
      out.write("\t\t\t\t\t<li><span></span>단백질</li>\r\n");
      out.write("\t\t\t\t\t<li><span></span>지방</li>\r\n");
      out.write("\t\t\t\t\t<li><span></span>당류</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"percentage_wrapper\">\r\n");
      out.write("\t\t\t\t<div id=\"percentage\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"wra\">0</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"wra\">0</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"wra\">0</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"wra\">0</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"wra\">0</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"wra\">0</span></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"slider\">\r\n");
      out.write("\t\t\t\t<div id=\"pie_chart\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c1_r\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_left\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c1_l\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_right\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c2_r\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_left\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c2_l\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_right\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c3_r\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_left\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c3_l\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_right\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c4_r\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_left\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c4_l\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_right\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c5_r\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_left\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"c5_l\"><p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pie_right\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
