/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-30 07:49:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class searchlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/ssafy/work_servlet_jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SafeFood_Web_Back_End_광주_3반_선한빛_임준형/WEB-INF/lib/jstl-1.2%20(1).jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/ssafy/work_servlet_jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SafeFood_Web_Back_End_광주_3반_선한빛_임준형/WEB-INF/lib/jstl-1.2%20(1).jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2 (1).jar", Long.valueOf(1569827813609L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>SafeFood</title>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./bootstrap-3.3.2-dist/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./bootstrap-3.3.2-dist/css/bootstrap-theme.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./css/main.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./js/custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-fixed-top\" style=\"background-color: #2e3537;\">\r\n");
      out.write("    <div class=\"col-md-1\"></div>\r\n");
      out.write("    <div class=\"col-md-10\" style=\"text-align: right;\">\r\n");
      out.write("        <button class=\"btn btn-sm dropdown-toggle glyphicon glyphicon-user\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\" style=\"background-color: #2c2c2c; color: #ffffff; margin: 7px\">&nbspLogin</button>\r\n");
      out.write("        <ul  class=\"dropdown-menu dropdown-menu-right\" style=\"border: 1px solid #252a2c; background: #2e3537;\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <form class=\"login-form margin-clear\" style=\"background: #2e3537; margin: 20px 20px;\">\r\n");
      out.write("                    <div class=\"form-group has-feedback\">\r\n");
      out.write("                        <label class=\"control-label\" style=\"color: #ffffff;\">아 이 디</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" >\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-user form-control-feedback\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group has-feedback\">\r\n");
      out.write("                        <label class=\"control-label\" style=\"color: #ffffff;\">비밀번호</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-user form-control-feedback\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-sm\" style=\"margin-bottom :20px\">로 그 인</button><br>\r\n");
      out.write("                        <a href=\"./find.html\"><button type=\"button\" class=\"btn btn-sm\" style=\"background-color: #2c2c2c; color: #ffffff;\">비밀번호 찾기</button></a>\r\n");
      out.write("                </form>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <a href=\"./signup.html\"><button class=\"btn btn-sm glyphicon glyphicon-user\" style=\"background-color: #2c2c2c; color: #ffffff; margin: 7px\">&nbsp회원가입</button></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-1\"></div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<body style=\"padding-top: 40px;\">\r\n");
      out.write("\t<!-- Navigation Bar -->\r\n");
      out.write("\t<div class=\"row\"\r\n");
      out.write("\t\tstyle=\"background-color: #ffffff; height: 100px; margin-top: 10px;\">\r\n");
      out.write("\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t<a href=\"./main.html\"><img src=\"../img/ssafy.png\" width=\"120px\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\" style=\"float: right;\">\r\n");
      out.write("\t\t\t\t<li><a href=\"./info.html\">공지 사항</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"./list_product.html\">상품 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">베스트 섭취 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">내 섭취 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">예상 섭취 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"glyphicon glyphicon-search\"></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 점보트론? -->\r\n");
      out.write("\t<div class=\"row\" style=\"background-color: #6C6C6C; height: 200px;\">\r\n");
      out.write("\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t<div class=\"col-md-10\"\r\n");
      out.write("\t\t\tstyle=\"color: white; margin: 30px; text-align: center;\">\r\n");
      out.write("\t\t\t<h2>WHAT WE PROVIDE</h2>\r\n");
      out.write("\t\t\t<div class=\"divide-line-center\"></div>\r\n");
      out.write("\t\t\t<p style=\"padding: 15px;\">건강한 삶을 위한 먹거리 프로젝트</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 검색 -->\r\n");
      out.write("\t<div class=\"row\" style=\"height: 100px; background-color: #373737;\">\r\n");
      out.write("\t\t<div class=\"col-md-4\"></div>\r\n");
      out.write("\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t<div class=\"row\" style=\"color: white; margin: 10px;\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\"\">검색 조건</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-7\">검색 단어</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" name=\"key\" id=\"key\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"name\" selected=\"selected\">상품명</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"maker\">제조사</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"material\">재료명</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"search-input\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-1\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" name=\"search\" class=\"btn btn-info\">검색</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-4\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 상품정보 리스트 -->\r\n");
      out.write("\t<section style=\"padding: 50px 0;\">\r\n");
      out.write("\t\t<div class=\"container-fluid\" style=\"margin-left: 120px;\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"main col-12\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"footer-main bg-dark py-5 small\">\r\n");
      out.write("\t\t<div class=\"container-fluid\" style=\"margin: 20px;\">\r\n");
      out.write("\t\t\t<h3>Find Us</h3>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<i class=\"glyphicon glyphicon-map-marker\">&nbsp</i><span>(SSAFY)\r\n");
      out.write("\t\t\t\t서울시 강남구 테헤란로 멀티스퀘어</span><br> <i class=\"glyphicon glyphicon-earphone\">&nbsp</i><span>1544-9001</span><br>\r\n");
      out.write("\t\t\t<i class=\"glyphicon glyphicon-envelope\">&nbsp</i><span>admin@ssafy.com</span><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /searchlist.jsp(115,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/searchlist.jsp(115,4) '${foodlist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${foodlist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /searchlist.jsp(115,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("food");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<div class=\"col-md-6\" style=\"margin-bottom: 50px;\"></div>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"card mb-3\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"row no-gutters\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${food.img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"200\" class=\"card-img\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"desc\"> <strong>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${food.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br />");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${food.maker }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</strong></span></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"title\"><a href=\"./nutrition.html\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${food.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></h3>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"card-description\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<i style=\"margin-left: 10px;\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-calendar\"></i>&nbspFeb,2017&nbsp&nbsp\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-tag\"></i>&nbspWeb,Design&nbsp\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<p\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 400px; height: 150px; margin-left: 10px; overflow: auto;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${food.material }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-info btn-sm\"><img src=\"img/add.png\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\twidth=\"15px\">추가</a> <a class=\"btn btn-info btn-sm\"><img\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"img/heart.png\" width=\"15px\">찜</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
